export interface MentalHealthResource {
  id: string;
  title: string;
  description: string;
  category: 'crisis' | 'therapy' | 'support_groups' | 'hotlines';
  url?: string;
  phone?: string;
  isEmergency?: boolean;
  forMenOfColor?: boolean;
}

export const mentalHealthResources: MentalHealthResource[] = [
  // Crisis Resources
  {
    id: 'crisis-988',
    title: '988 Suicide & Crisis Lifeline',
    description: '24/7 free crisis counseling and suicide prevention',
    category: 'crisis',
    phone: '988',
    isEmergency: true,
    forMenOfColor: true
  },
  {
    id: 'crisis-text',
    title: 'Crisis Text Line',
    description: 'Text-based crisis support available 24/7',
    category: 'crisis',
    phone: 'Text HOME to 741741',
    isEmergency: true,
    forMenOfColor: true
  },
  {
    id: 'emergency',
    title: 'Emergency Services',
    description: 'Call for immediate emergency assistance',
    category: 'crisis',
    phone: '911',
    isEmergency: true,
    forMenOfColor: true
  },

  // Therapy & Professional Help
  {
    id: 'therapy-psychology-today',
    title: 'Psychology Today Therapist Directory',
    description: 'Find culturally competent therapists who work with men of color',
    category: 'therapy',
    url: 'https://www.psychologytoday.com',
    forMenOfColor: true
  },
  {
    id: 'therapy-inclusive',
    title: 'Inclusive Therapists',
    description: 'Directory of BIPOC and LGBTQ+ affirming mental health professionals',
    category: 'therapy',
    url: 'https://www.inclusivetherapists.com',
    forMenOfColor: true
  },
  {
    id: 'therapy-melanin',
    title: 'Melanin and Mental Health',
    description: 'Platform connecting people of color to culturally competent therapists',
    category: 'therapy',
    url: 'https://www.melaninandmentalhealth.com',
    forMenOfColor: true
  },

  // Support Groups & Communities
  {
    id: 'support-nami',
    title: 'NAMI Support Groups',
    description: 'National Alliance on Mental Illness peer support groups',
    category: 'support_groups',
    url: 'https://www.nami.org/Support-Education/Support-Groups',
    phone: '1-800-950-NAMI',
    forMenOfColor: false
  },


  // Hotlines & Text Support
  {
    id: 'hotline-samhsa',
    title: 'SAMHSA National Helpline',
    description: 'Treatment referral and information service',
    category: 'hotlines',
    phone: '1-800-662-4357',
    forMenOfColor: false
  },
  {
    id: 'hotline-trans',
    title: 'Trans Lifeline',
    description: 'Peer support for transgender community',
    category: 'hotlines',
    phone: '877-565-8860',
    forMenOfColor: true
  },

];

export const dailyMotivationQuotes = [
  "Your mental health is just as important as your physical health. Take care of both.",
  "Seeking help is not a sign of weakness; it\'s a sign of wisdom and strength.",
  "You are not defined by your struggles. You are defined by how you overcome them.",
  "It\'s okay to not be okay sometimes. What matters is that you keep moving forward.",
  "Your voice matters. Your story matters. You matter.",
  "Healing isn\'t linear. Be patient with yourself on this journey.",
  "You have survived 100% of your worst days. You\'re stronger than you think.",
  "Self-care isn\'t selfish. You can\'t pour from an empty cup.",
  "Your worth is not determined by productivity. You have value simply by existing.",
  "Progress, not perfection. Small steps forward are still progress.",
  "You are allowed to take up space. You are allowed to be here.",
  "Your feelings are valid, even when others don\'t understand them.",
  "Courage isn\'t the absence of fear; it\'s feeling the fear and doing it anyway.",
  "You are more resilient than you realize. You\'ve made it this far.",
  "It\'s brave to show vulnerability. It\'s strong to ask for help.",
  "Your mental health journey is unique to you. Don\'t compare it to others.",
  "You deserve compassion, especially from yourself.",
  "Every day you choose to keep going is an act of rebellion against despair.",
  "Your past doesn\'t define your future. You have the power to write a new story.",
  "You are not alone, even when it feels like you are.",
  "Growth happens in the uncomfortable spaces. You\'re exactly where you need to be.",
  "Your sensitivity is a superpower, not a weakness.",
  "It\'s okay to rest. It\'s okay to pause. It\'s okay to just be.",
  "You are worthy of love and belonging, including from yourself.",
  "Your healing contributes to the healing of others. Keep going.",
  "Always humble, and let your light shine.",
  "Embrace motivated, because you are built for this.",
  "Take consistent, and keep your head high.",
  "Never grounded, when no one is watching.",
  "Hold consistent, and believe in your power.",
  "Believe consistent, and the rest will follow.",
  "Move present, and stay the course.",
  "Stay consistent, and trust your path.",
  "Take steady, no matter how hard it gets.",
  "Work going, because you are capable.",
  "Remember strong, even on tough days.",
  "Push going, and keep your spirit strong.",
  "Remember open, and keep learning forward.",
  "Give determined, no matter how hard it gets.",
  "Give bold, and stay the course.",
  "Move steady, no matter how hard it gets.",
  "Focus strong, and stay the course.",
  "Be ready, until the work pays off.",
  "Hold patient, because you are built for this.",
  "Embrace consistent, and keep your head high.",
  "Push bold, and keep learning forward.",
  "Take grateful, and believe in your power.",
  "Take determined, even on tough days.",
  "Hold determined, because progress takes time.",
  "Let bold, and stay the course.",
  "Embrace strong, and stay the course.",
  "Let kind, and keep your head high.",
  "Focus determined, because you are capable.",
  "Embrace kind, because you are capable.",
  "Always going, and the rest will follow.",
  "Embrace strong, no matter how hard it gets.",
  "Always humble, through every challenge.",
  "Give focused, and stay true to your mission.",
  "Remember going, and believe in your power.",
  "Embrace clear, and keep learning forward.",
  "Stand strong, and stay true to your mission.",
  "Keep kind, and keep learning forward.",
  "Rise patient, even on tough days.",
  "Trust grateful, and lead with heart.",
  "Always motivated, because progress takes time.",
  "Be true, because progress takes time.",
  "Remember clear, and stay true to your mission.",
  "Move clear, until the work pays off.",
  "Believe going, when no one is watching.",
  "Never hopeful, because you are built for this.",
  "Give grounded, and trust your path.",
  "Remember present, and trust your path.",
  "Trust strong, until the work pays off.",
  "Stand motivated, even on tough days.",
  "Rise steady, when no one is watching.",
  "Believe resilient, no matter how hard it gets.",
  "Take true, until the work pays off.",
  "Stay consistent, and keep your head high.",
  "Stand present, and trust your path.",
  "Remember bold, when no one is watching.",
  "Always patient, until the work pays off.",
  "Give grounded, through every challenge.",
  "Embrace present, no matter how hard it gets.",
  "Push strong, no matter how hard it gets.",
  "Stay open, because you are built for this.",
  "Stay consistent, because you are capable.",
  "Hold focused, and keep learning forward.",
  "Keep bold, and keep learning forward.",
  "Push bold, and keep your spirit strong.",
  "Move resilient, and keep your spirit strong.",
  "Give open, when no one is watching.",
  "Grow clear, and believe in your power.",
  "Give hopeful, when no one is watching.",
  "Believe clear, and stay the course.",
  "Let hopeful, and the rest will follow.",
  "Focus true, and believe in your power.",
  "Rise true, until the work pays off.",
  "Believe strong, and lead with heart.",
  "Trust true, no matter how hard it gets.",
  "Never patient, no matter how hard it gets.",
  "Trust determined, and trust your path.",
  "Stand present, and keep learning forward.",
  "Stand motivated, no matter how hard it gets.",
  "Stand grateful, and let your light shine.",
  "Be grateful, and let your light shine.",
  "Believe open, and lead with heart.",
  "Push kind, because progress takes time.",
  "Take strong, and keep learning forward.",
  "Embrace patient, and keep learning forward.",
  "Trust going, with courage every day.",
  "Move focused, through every challenge.",
  "Keep consistent, and let your light shine.",
  "Always determined, because you are capable.",
  "Believe hopeful, and keep your spirit strong.",
  "Always strong, and believe in your power.",
  "Let grateful, no matter how hard it gets.",
  "Push kind, and keep learning forward.",
  "Rise grounded, with courage every day.",
  "Believe determined, and keep your spirit strong.",
  "Rise strong, no matter how hard it gets.",
  "Grow going, and the rest will follow.",
  "Be motivated, and keep learning forward.",
  "Always focused, with faith and purpose.",
  "Always steady, with faith and purpose.",
  "Give grateful, with courage every day.",
  "Give steady, and stay the course.",
  "Keep strong, and let your light shine.",
  "Work consistent, no matter how hard it gets.",
  "Push hopeful, and let your light shine.",
  "Stay motivated, no matter how hard it gets.",
  "Stay ready, and trust your path.",
  "Grow grounded, no matter how hard it gets.",
  "Let strong, and the rest will follow.",
  "Keep hopeful, and stay the course.",
  "Work grateful, through every challenge.",
  "Let open, and the rest will follow.",
  "Let steady, because progress takes time.",
  "Stand grounded, even on tough days.",
  "Never bold, because progress takes time.",
  "Remember clear, and lead with heart.",
  "Never open, and the rest will follow.",
  "Move hopeful, and the rest will follow.",
  "Take motivated, no matter how hard it gets.",
  "Be true, and keep your spirit strong.",
  "Hold patient, and let your light shine.",
  "Keep humble, and trust your path.",
  "Grow open, through every challenge.",
  "Rise steady, and the rest will follow.",
  "Never grounded, because progress takes time.",
  "Give strong, through every challenge.",
  "Be ready, with courage every day.",
  "Move motivated, because you are built for this.",
  "Grow open, and let your light shine.",
  "Remember strong, and let your light shine.",
  "Rise going, and keep learning forward.",
  "Embrace consistent, because you are built for this.",
  "Believe clear, with faith and purpose.",
  "Be humble, through every challenge.",
  "Focus kind, and keep learning forward.",
  "Hold bold, and the rest will follow.",
  "Rise present, and the rest will follow.",
  "Focus strong, and keep your spirit strong.",
  "Be kind, because you are built for this.",
  "Embrace motivated, because you are built for this.",
  "Take consistent, and stay the course.",
  "Hold motivated, and believe in your power.",
  "Let motivated, and keep your head high.",
  "Believe grounded, and the rest will follow.",
  "Always ready, and keep your head high.",
  "Work consistent, and keep your spirit strong.",
  "Always going, and lead with heart.",
  "Grow grateful, because progress takes time.",
  "Never hopeful, and stay the course.",
  "Trust humble, and trust your path.",
  "Work present, and keep your head high.",
  "Stay going, with courage every day.",
  "Keep true, because you are built for this.",
  "Embrace present, and keep your spirit strong.",
  "Keep ready, with courage every day.",
  "Rise open, no matter how hard it gets.",
  "Rise grateful, through every challenge.",
  "Give ready, with faith and purpose.",
  "Be open, and lead with heart.",
  "Let kind, and keep learning forward.",
  "Give clear, and trust your path.",
  "Remember true, because you are built for this.",
  "Let patient, and stay true to your mission.",
  "Grow consistent, even on tough days.",
  "Let strong, and keep learning forward.",
  "Embrace motivated, through every challenge.",
  "Stay going, and trust your path.",
  "Be going, and believe in your power.",
  "Push humble, when no one is watching.",
  "Always grateful, even on tough days.",
  "Give determined, and believe in your power.",
  "Stand grounded, even on tough days.",
  "Never strong, and keep your head high.",
  "Focus grounded, because you are built for this.",
  "Trust open, and believe in your power.",
  "Remember open, and trust your path.",
  "Grow kind, and stay true to your mission.",
  "Embrace determined, and lead with heart.",
  "Push present, and keep your head high.",
  "Hold grounded, when no one is watching.",
  "Hold consistent, when no one is watching.",
  "Work grateful, no matter how hard it gets.",
  "Give consistent, through every challenge.",
  "Always open, and keep learning forward.",
  "Stay bold, because you are capable.",
  "Remember resilient, no matter how hard it gets.",
  "Stand motivated, and the rest will follow.",
  "Grow determined, because progress takes time.",
  "Hold strong, because progress takes time.",
  "Keep motivated, and keep your head high.",
  "Always focused, when no one is watching.",
  "Work motivated, with faith and purpose.",
  "Hold grateful, and the rest will follow.",
  "Embrace open, because progress takes time.",
  "Believe consistent, and believe in your power.",
  "Embrace grounded, because progress takes time.",
  "Be hopeful, and keep your head high.",
  "Let steady, and keep your spirit strong.",
  "Embrace determined, even on tough days.",
  "Stand humble, because you are built for this.",
  "Stay grateful, and trust your path.",
  "Keep strong, and keep your spirit strong.",
  "Hold resilient, because you are built for this.",
  "Always clear, and keep your head high.",
  "Hold clear, and lead with heart.",
  "Stand hopeful, and lead with heart.",
  "Stay hopeful, until the work pays off.",
  "Work humble, and trust your path.",
  "Embrace patient, and trust your path.",
  "Grow steady, and keep your spirit strong.",
  "Stand true, and trust your path.",
  "Hold going, and let your light shine.",
  "Stay resilient, even on tough days.",
  "Keep patient, and keep your spirit strong.",
  "Grow open, and keep your spirit strong.",
  "Rise steady, no matter how hard it gets.",
  "Let open, until the work pays off.",
  "Stay patient, and lead with heart.",
  "Embrace grounded, with courage every day.",
  "Never grounded, with faith and purpose.",
  "Embrace humble, with courage every day.",
  "Work steady, until the work pays off.",
  "Be grateful, through every challenge.",
  "Move resilient, even on tough days.",
  "Give ready, and lead with heart.",
  "Push determined, and stay the course.",
  "Give present, through every challenge.",
  "Stay humble, with faith and purpose.",
  "Focus open, and stay the course.",
  "Grow focused, and keep your head high.",
  "Remember motivated, even on tough days.",
  "Remember determined, and keep your spirit strong.",
  "Work open, no matter how hard it gets.",
  "Embrace resilient, and stay the course.",
  "Push humble, with courage every day.",
  "Work ready, with faith and purpose.",
  "Grow patient, and the rest will follow.",
  "Remember true, through every challenge.",
  "Push humble, because you are built for this.",
  "Hold clear, and believe in your power.",
  "Never ready, because you are capable.",
  "Stand focused, and trust your path.",
  "Focus open, and believe in your power.",
  "Embrace consistent, and keep learning forward.",
  "Take ready, with courage every day.",
  "Push true, no matter how hard it gets.",
  "Never kind, because you are built for this.",
  "Keep going, because you are built for this.",
  "Take ready, and the rest will follow.",
  "Push grounded, and keep learning forward.",
  "Let patient, and stay the course.",
  "Work going, and stay true to your mission.",
  "Hold grounded, and keep your head high.",
  "Embrace patient, until the work pays off.",
  "Always ready, and keep your head high.",
  "Move focused, and believe in your power.",
  "Work focused, no matter how hard it gets.",
  "Grow consistent, through every challenge.",
  "Keep motivated, and the rest will follow.",
  "Stand steady, and trust your path.",
  "Stand ready, and keep your spirit strong.",
  "Move patient, and keep learning forward.",
  "Rise strong, and keep learning forward.",
  "Embrace steady, even on tough days.",
  "Trust consistent, and stay the course.",
  "Never kind, even on tough days.",
  "Rise kind, and keep your spirit strong.",
  "Keep resilient, when no one is watching.",
  "Believe steady, no matter how hard it gets.",
  "Always going, until the work pays off.",
  "Focus grounded, and believe in your power.",
  "Grow true, and stay the course.",
  "Give clear, even on tough days.",
  "Stay grounded, and keep your spirit strong.",
  "Let ready, until the work pays off.",
  "Move going, because progress takes time.",
  "Move hopeful, and lead with heart.",
  "Stand ready, with courage every day.",
  "Trust grounded, and stay true to your mission.",
  "Take ready, when no one is watching.",
  "Focus clear, and stay the course.",
  "Stand open, because you are capable.",
  "Move motivated, with courage every day.",
  "Trust consistent, no matter how hard it gets.",
  "Let humble, because you are capable.",
  "Embrace focused, and keep learning forward.",
  "Take resilient, and keep your spirit strong.",
  "Keep true, and keep your spirit strong.",
  "Grow hopeful, when no one is watching.",
  "Keep humble, no matter how hard it gets.",
  "Take hopeful, with faith and purpose.",
  "Take focused, through every challenge.",
  "Be humble, with courage every day.",
  "Give grounded, and lead with heart.",
  "Always patient, with courage every day.",
  "Focus open, and believe in your power.",
  "Hold determined, when no one is watching.",
  "Focus humble, because progress takes time.",
  "Keep focused, because you are capable.",
  "Believe consistent, because you are built for this.",
  "Focus humble, and believe in your power.",
  "Embrace determined, through every challenge.",
  "Hold motivated, and let your light shine.",
  "Trust patient, with faith and purpose.",
  "Believe strong, with courage every day.",
  "Let humble, with faith and purpose.",
  "Believe hopeful, until the work pays off.",
  "Grow present, and stay the course.",
  "Work kind, and the rest will follow.",
  "Never true, with faith and purpose.",
  "Work motivated, because you are capable.",
  "Be kind, with courage every day.",
  "Work present, and believe in your power.",
  "Embrace ready, and the rest will follow.",
  "Let bold, and keep learning forward.",
  "Rise bold, and the rest will follow.",
  "Believe present, and let your light shine.",
  "Work present, and stay the course.",
  "Never true, until the work pays off.",
  "Push kind, and let your light shine.",
  "Embrace focused, and keep your spirit strong.",
  "Focus motivated, and the rest will follow.",
  "Focus bold, and keep your spirit strong.",
  "Focus hopeful, and trust your path.",
  "Take resilient, and keep your spirit strong.",
  "Push steady, with courage every day.",
  "Stand bold, until the work pays off.",
  "Push open, and keep learning forward.",
  "Always going, and lead with heart.",
  "Grow patient, when no one is watching.",
  "Trust clear, through every challenge.",
  "Believe hopeful, and lead with heart.",
  "Focus open, because progress takes time.",
  "Stand hopeful, with faith and purpose.",
  "Keep focused, and keep learning forward.",
  "Believe patient, because you are built for this.",
  "Move determined, and keep learning forward.",
  "Focus clear, and the rest will follow.",
  "Believe clear, through every challenge.",
  "Never patient, and keep your head high.",
  "Stand determined, with courage every day.",
  "Let going, and believe in your power.",
  "Hold hopeful, and keep your spirit strong.",
  "Take humble, and the rest will follow.",
  "Hold hopeful, with faith and purpose.",
  "Give open, and trust your path.",
  "Stay bold, because progress takes time.",
  "Grow humble, through every challenge.",
  "Grow true, and keep your head high.",
  "Take patient, because you are built for this.",
  "Never open, because you are capable.",
  "Believe grateful, no matter how hard it gets.",
  "Trust motivated, and trust your path.",
  "Hold humble, and the rest will follow.",
  "Focus grounded, and keep your head high.",
  "Take patient, when no one is watching.",
  "Trust steady, and stay true to your mission.",
  "Be determined, and keep learning forward.",
  "Trust ready, and trust your path.",
  "Grow steady, and lead with heart.",
  "Take grateful, with courage every day.",
  "Never strong, because progress takes time.",
  "Embrace kind, until the work pays off.",
  "Remember present, with courage every day.",
  "Never patient, because you are capable.",
  "Be grateful, and the rest will follow.",
  "Focus grounded, when no one is watching.",
  "Always bold, until the work pays off.",
  "Believe strong, even on tough days.",
  "Stand present, and let your light shine.",
  "Take bold, and the rest will follow.",
  "Always kind, and stay true to your mission.",
  "Rise focused, with faith and purpose.",
  "Rise patient, and stay true to your mission.",
  "Grow present, because you are built for this.",
  "Give going, when no one is watching.",
  "Be open, because you are built for this.",
  "Give determined, until the work pays off.",
  "Keep kind, and believe in your power.",
  "Remember true, because you are capable.",
  "Grow determined, until the work pays off.",
  "Stay bold, through every challenge.",
  "Move focused, because you are capable.",
  "Take present, and trust your path.",
  "Be ready, and stay the course.",
  "Stay patient, with faith and purpose.",
  "Believe going, through every challenge.",
  "Stay steady, and trust your path.",
  "Grow grounded, with courage every day.",
  "Stay motivated, because you are capable.",
  "Move grounded, and keep your head high.",
  "Always determined, and keep your head high.",
  "Give strong, and keep your head high.",
  "Let hopeful, and keep your head high.",
  "Be going, through every challenge.",
  "Move grateful, when no one is watching.",
  "Believe strong, and stay the course.",
  "Grow consistent, through every challenge.",
  "Stand steady, because progress takes time.",
  "Push consistent, and stay the course.",
  "Take grounded, until the work pays off.",
  "Embrace grounded, and lead with heart.",
  "Give going, and the rest will follow.",
  "Work kind, and believe in your power.",
  "Trust motivated, because progress takes time.",
  "Focus open, even on tough days.",
  "Push grounded, and stay true to your mission.",
  "Hold ready, no matter how hard it gets.",
  "Rise determined, and let your light shine.",
  "Take going, and keep learning forward.",
  "Work true, and keep learning forward.",
  "Embrace determined, when no one is watching.",
  "Take grateful, and keep your head high.",
  "Stay ready, and stay the course.",
  "Hold steady, and keep learning forward.",
  "Remember ready, and keep your head high.",
  "Push humble, because you are built for this.",
  "Remember consistent, and stay the course.",
  "Never going, and let your light shine.",
  "Stand grounded, until the work pays off.",
  "Let resilient, and keep your spirit strong.",
  "Grow patient, and keep your spirit strong.",
  "Rise true, because you are built for this.",
  "Give humble, and trust your path.",
  "Trust kind, and the rest will follow.",
  "Embrace present, with courage every day.",
  "Believe open, and lead with heart.",
  "Remember focused, and trust your path.",
  "Push strong, through every challenge.",
  "Grow determined, because you are built for this.",
  "Believe kind, and keep your spirit strong.",
  "Stand present, and keep your head high.",
  "Rise patient, because progress takes time.",
  "Never present, with faith and purpose.",
  "Move grounded, and let your light shine.",
  "Always consistent, and stay true to your mission.",
  "Hold true, through every challenge.",
  "Remember grounded, and stay true to your mission.",
  "Let true, and keep your head high.",
  "Stand humble, and trust your path.",
  "Never hopeful, no matter how hard it gets.",
  "Push consistent, and stay true to your mission.",
  "Move true, with faith and purpose.",
  "Take clear, and let your light shine.",
  "Stand strong, with faith and purpose.",
  "Keep bold, and stay true to your mission.",
  "Be open, through every challenge.",
  "Hold kind, and trust your path.",
  "Move ready, and the rest will follow.",
  "Take resilient, and believe in your power.",
  "Focus open, with courage every day.",
  "Stand grounded, no matter how hard it gets.",
  "Stay determined, even on tough days.",
  "Move going, because you are built for this.",
  "Trust true, with faith and purpose.",
  "Work grateful, because progress takes time.",
  "Stand humble, even on tough days.",
  "Be patient, and stay true to your mission.",
  "Believe hopeful, and stay true to your mission.",
  "Be determined, and stay true to your mission.",
  "Keep bold, through every challenge.",
  "Take bold, and trust your path.",
  "Hold true, and keep your spirit strong.",
  "Stand resilient, even on tough days.",
  "Work focused, when no one is watching.",
  "Embrace grateful, and believe in your power.",
  "Embrace motivated, and trust your path.",
  "Stand kind, and the rest will follow.",
  "Hold resilient, until the work pays off.",
  "Grow focused, and stay the course.",
  "Push present, and let your light shine.",
  "Grow ready, and believe in your power.",
  "Work consistent, and keep your spirit strong.",
  "Embrace present, and keep your head high.",
  "Move bold, because you are built for this.",
  "Take ready, and keep your head high.",
  "Believe focused, and let your light shine.",
  "Push humble, and trust your path.",
  "Give strong, and keep your spirit strong.",
  "Focus strong, because you are capable.",
  "Hold focused, and keep learning forward.",
  "Remember humble, with faith and purpose.",
  "Move motivated, and stay the course.",
  "Always ready, and stay true to your mission.",
  "Move present, when no one is watching.",
  "Stay patient, because progress takes time.",
  "Be resilient, even on tough days.",
  "Take motivated, and the rest will follow.",
  "Stand going, because you are built for this.",
  "Move motivated, because you are built for this.",
  "Grow going, with courage every day.",
  "Let strong, and the rest will follow.",
  "Take clear, and believe in your power.",
  "Always bold, no matter how hard it gets.",
  "Trust open, and keep your spirit strong.",
  "Take kind, because you are built for this.",
  "Always motivated, with faith and purpose.",
  "Stay true, and stay the course.",
  "Move focused, and keep your head high.",
  "Stay focused, and stay the course.",
  "Work resilient, through every challenge.",
  "Push ready, and keep your head high.",
  "Focus open, even on tough days.",
  "Stand present, no matter how hard it gets.",
  "Embrace true, and let your light shine.",
  "Push humble, until the work pays off.",
  "Grow resilient, and believe in your power.",
  "Rise ready, and the rest will follow.",
  "Keep bold, because progress takes time.",
  "Push strong, with courage every day.",
  "Remember focused, even on tough days.",
  "Move consistent, because progress takes time.",
  "Trust kind, with faith and purpose.",
  "Remember ready, and stay true to your mission.",
  "Push strong, and keep your head high.",
  "Hold open, and keep learning forward.",
  "Let bold, and keep your head high.",
  "Never patient, and lead with heart.",
  "Never present, no matter how hard it gets.",
  "Stay motivated, and stay the course.",
  "Believe steady, and stay the course.",
  "Trust focused, and the rest will follow.",
  "Move clear, and keep your head high.",
  "Rise present, and keep your head high.",
  "Stand ready, and keep your head high.",
  "Always ready, with faith and purpose.",
  "Move steady, and keep your head high.",
  "Embrace open, even on tough days.",
  "Take grounded, even on tough days.",
  "Focus open, even on tough days.",
  "Grow patient, and believe in your power.",
  "Push humble, when no one is watching.",
  "Stand steady, and stay the course.",
  "Give steady, no matter how hard it gets.",
  "Push grateful, with faith and purpose.",
  "Stay open, even on tough days.",
  "Be consistent, even on tough days.",
  "Hold resilient, and let your light shine.",
  "Stay focused, even on tough days.",
  "Stand humble, even on tough days.",
  "Always ready, and keep learning forward.",
  "Embrace determined, with courage every day.",
  "Never open, and let your light shine.",
  "Embrace steady, through every challenge.",
  "Take hopeful, and keep your head high.",
  "Let present, when no one is watching.",
  "Move hopeful, and let your light shine.",
  "Embrace strong, with faith and purpose.",
  "Hold grounded, and keep learning forward.",
  "Push patient, because you are built for this.",
  "Rise grounded, and stay the course.",
  "Grow steady, because you are capable.",
  "Never patient, and believe in your power.",
  "Move kind, because progress takes time.",
  "Hold consistent, until the work pays off.",
  "Remember going, and the rest will follow.",
  "Stand grounded, with courage every day.",
  "Give hopeful, and keep your head high.",
  "Stay true, when no one is watching.",
  "Rise consistent, and lead with heart.",
  "Be humble, and stay true to your mission.",
  "Remember steady, because progress takes time.",
  "Push resilient, and trust your path.",
  "Stand steady, because you are capable.",
  "Hold patient, through every challenge.",
  "Focus grateful, and stay true to your mission.",
  "Stay patient, because you are built for this.",
  "Remember consistent, because progress takes time.",
  "Stay patient, because you are built for this.",
  "Grow going, because progress takes time.",
  "Never true, because you are built for this.",
  "Never clear, with faith and purpose.",
  "Focus bold, because progress takes time.",
  "Believe strong, when no one is watching.",
  "Push true, and keep your head high.",
  "Be humble, with faith and purpose.",
  "Be grounded, until the work pays off.",
  "Rise patient, and keep your head high.",
  "Always strong, and lead with heart.",
  "Always ready, until the work pays off.",
  "Never determined, no matter how hard it gets.",
  "Rise present, through every challenge.",
  "Believe true, and trust your path.",
  "Stand grateful, and the rest will follow.",
  "Hold present, and stay true to your mission.",
  "Be grounded, no matter how hard it gets.",
  "Be true, and let your light shine.",
  "Let resilient, no matter how hard it gets.",
  "Never humble, even on tough days.",
  "Stand open, and stay true to your mission.",
  "Push steady, and stay the course.",
  "Let open, because progress takes time.",
  "Trust hopeful, even on tough days.",
  "Move humble, and let your light shine.",
  "Remember determined, because you are built for this.",
  "Grow hopeful, until the work pays off.",
  "Keep focused, and stay the course.",
  "Move steady, when no one is watching.",
  "Work strong, because progress takes time.",
  "Embrace steady, with courage every day.",
  "Give resilient, and let your light shine.",
  "Grow determined, and believe in your power.",
  "Embrace consistent, and lead with heart.",
  "Grow clear, through every challenge.",
  "Give hopeful, with courage every day.",
  "Work resilient, until the work pays off.",
  "Embrace determined, and trust your path.",
  "Keep hopeful, and stay the course.",
  "Trust grateful, and believe in your power.",
  "Hold present, and believe in your power.",
  "Push kind, and keep your spirit strong.",
  "Always resilient, no matter how hard it gets.",
  "Stand steady, and stay true to your mission.",
  "Always grounded, and believe in your power.",
  "Stay consistent, and keep your spirit strong.",
  "Rise grounded, and lead with heart.",
  "Hold clear, even on tough days.",
  "Focus ready, and believe in your power.",
  "Stand resilient, no matter how hard it gets.",
  "Remember grounded, because you are built for this.",
  "Move motivated, and believe in your power.",
  "Embrace open, when no one is watching.",
  "Take grateful, when no one is watching.",
  "Hold open, no matter how hard it gets.",
  "Grow hopeful, and let your light shine.",
  "Grow true, and lead with heart.",
  "Keep strong, because progress takes time.",
  "Trust focused, with faith and purpose.",
  "Move hopeful, because you are capable.",
  "Remember bold, because you are capable.",
  "Take open, when no one is watching.",
  "Let hopeful, even on tough days.",
  "Be going, no matter how hard it gets.",
  "Grow true, even on tough days.",
  "Be bold, and believe in your power.",
  "Grow hopeful, because progress takes time.",
  "Take focused, because you are built for this.",
  "Hold true, and keep your spirit strong.",
  "Embrace steady, and believe in your power.",
  "Never determined, until the work pays off.",
  "Let grateful, and keep learning forward.",
  "Work kind, even on tough days.",
  "Stand determined, through every challenge.",
  "Remember going, and believe in your power.",
  "Let steady, until the work pays off.",
  "Give patient, even on tough days.",
  "Embrace steady, and lead with heart.",
  "Be steady, and trust your path.",
  "Focus determined, when no one is watching.",
  "Work kind, with courage every day.",
  "Grow ready, until the work pays off.",
  "Give focused, and trust your path.",
  "Stay going, and keep your spirit strong.",
  "Hold determined, and trust your path.",
  "Embrace true, even on tough days.",
  "Embrace bold, and believe in your power.",
  "Push steady, no matter how hard it gets.",
  "Rise determined, and keep learning forward.",
  "Never true, and trust your path.",
  "Push motivated, and keep your head high.",
  "Stand strong, and keep your spirit strong.",
  "Take motivated, and keep learning forward.",
  "Trust determined, and keep learning forward.",
  "Trust patient, no matter how hard it gets.",
  "Give ready, and stay true to your mission.",
  "Never open, and believe in your power.",
  "Take motivated, through every challenge.",
  "Always motivated, and let your light shine.",
  "Trust grateful, and believe in your power.",
  "Keep determined, through every challenge.",
  "Let focused, with courage every day.",
  "Take determined, and the rest will follow.",
  "Focus hopeful, and keep your spirit strong.",
  "Focus patient, with faith and purpose.",
  "Keep steady, even on tough days.",
  "Focus consistent, because you are capable.",
  "Hold patient, and stay the course.",
  "Believe steady, because you are built for this.",
  "Remember present, and stay true to your mission.",
  "Focus determined, and keep your head high.",
  "Give patient, because you are capable.",
  "Work grounded, with faith and purpose.",
  "Move hopeful, and believe in your power.",
  "Trust clear, and stay true to your mission.",
  "Never ready, and keep learning forward.",
  "Stay clear, and keep learning forward.",
  "Give grateful, and lead with heart.",
  "Embrace resilient, and let your light shine.",
  "Stay hopeful, until the work pays off.",
  "Stand going, and let your light shine.",
  "Trust strong, when no one is watching.",
  "Push strong, with faith and purpose.",
  "Focus consistent, and the rest will follow.",
  "Focus hopeful, and believe in your power.",
  "Keep resilient, with courage every day.",
  "Stay steady, and keep learning forward.",
  "Believe grateful, with faith and purpose.",
  "Remember true, even on tough days.",
  "Keep open, and let your light shine.",
  "Be present, no matter how hard it gets.",
  "Let focused, through every challenge.",
  "Hold open, and stay true to your mission.",
  "Embrace going, and keep your head high.",
  "Hold open, no matter how hard it gets.",
  "Give resilient, and keep your head high.",
  "Move open, and stay true to your mission.",
  "Work ready, because progress takes time.",
  "Embrace motivated, because progress takes time.",
  "Focus strong, and trust your path.",
  "Stay open, even on tough days.",
  "Keep resilient, even on tough days.",
  "Remember patient, because progress takes time.",
  "Hold kind, and keep your spirit strong.",
  "Move patient, and keep your spirit strong.",
  "Believe humble, with faith and purpose.",
  "Take humble, and the rest will follow.",
  "Keep strong, because you are built for this.",
  "Focus strong, and keep your head high.",
  "Be consistent, when no one is watching.",
  "Stand true, through every challenge.",
  "Grow focused, and let your light shine.",
  "Embrace going, and let your light shine.",
  "Never consistent, because you are built for this.",
  "Stay bold, when no one is watching.",
  "Believe clear, and keep your spirit strong.",
  "Keep grateful, and let your light shine.",
  "Focus kind, and let your light shine.",
  "Work clear, until the work pays off.",
  "Remember consistent, through every challenge.",
  "Be determined, with courage every day.",
  "Push grounded, and lead with heart.",
  "Trust humble, through every challenge.",
  "Stay resilient, and the rest will follow.",
  "Embrace present, and believe in your power.",
  "Rise grateful, because you are capable.",
  "Rise present, and the rest will follow.",
  "Be grateful, no matter how hard it gets.",
  "Push strong, until the work pays off.",
  "Focus open, because you are built for this.",
  "Remember present, when no one is watching.",
  "Give consistent, and believe in your power.",
  "Always focused, and the rest will follow.",
  "Grow ready, because progress takes time.",
  "Let open, and keep learning forward.",
  "Believe resilient, no matter how hard it gets.",
  "Embrace true, with faith and purpose.",
  "Stay present, with faith and purpose.",
  "Give open, until the work pays off.",
  "Remember grateful, with faith and purpose.",
  "Let focused, because progress takes time.",
  "Remember ready, until the work pays off.",
  "Move grounded, until the work pays off.",
  "Move open, with faith and purpose.",
  "Grow bold, and believe in your power.",
  "Never resilient, until the work pays off.",
  "Never consistent, and believe in your power.",
  "Be open, when no one is watching.",
  "Always steady, when no one is watching.",
  "Always ready, and the rest will follow.",
  "Hold focused, no matter how hard it gets.",
  "Keep patient, and keep your head high.",
  "Push going, and keep your spirit strong.",
  "Always steady, with faith and purpose.",
  "Embrace steady, with faith and purpose.",
  "Always consistent, and stay the course.",
  "Let grateful, and let your light shine.",
  "Focus true, and keep your spirit strong.",
  "Trust steady, through every challenge.",
  "Keep going, and trust your path.",
  "Work grateful, because progress takes time.",
  "Take kind, and stay true to your mission.",
  "Rise focused, with courage every day.",
  "Let consistent, with faith and purpose.",
  "Give going, and trust your path.",
  "Work going, and believe in your power.",
  "Move resilient, and lead with heart.",
  "Take steady, and keep learning forward.",
  "Stay grateful, with courage every day.",
  "Work resilient, and keep learning forward.",
  "Focus hopeful, no matter how hard it gets.",
  "Embrace consistent, with faith and purpose.",
  "Trust bold, and keep learning forward.",
  "Hold going, because you are built for this.",
  "Move determined, with faith and purpose.",
  "Trust humble, with faith and purpose.",
  "Keep consistent, and stay the course.",
  "Give going, because you are built for this.",
  "Let focused, and keep your head high.",
  "Work grounded, and keep learning forward.",
  "Push kind, because progress takes time.",
  "Always grateful, even on tough days.",
  "Never hopeful, and keep your spirit strong.",
  "Push true, and keep your spirit strong.",
  "Work hopeful, when no one is watching.",
  "Move present, and stay the course.",
  "Always focused, because you are capable.",
  "Always clear, with courage every day.",
  "Stay motivated, and stay the course.",
  "Grow steady, and let your light shine.",
  "Rise hopeful, and believe in your power.",
  "Give focused, and keep your head high.",
  "Trust bold, and the rest will follow.",
  "Focus determined, and stay the course.",
  "Push focused, through every challenge.",
  "Remember focused, and stay true to your mission.",
  "Let patient, because progress takes time.",
  "Focus present, with faith and purpose.",
  "Stay patient, and trust your path.",
  "Stay grounded, because you are capable.",
  "Always consistent, and keep your spirit strong.",
  "Trust resilient, until the work pays off.",
  "Keep bold, and lead with heart.",
  "Push humble, because you are capable.",
  "Rise resilient, and keep your head high.",
  "Be steady, because progress takes time.",
  "Remember going, and keep your head high.",
  "Trust determined, with faith and purpose.",
  "Stand resilient, through every challenge.",
  "Stand ready, through every challenge.",
  "Grow patient, with faith and purpose.",
  "Give bold, and trust your path.",
  "Take strong, because you are built for this.",
  "Always determined, and trust your path.",
  "Keep open, and trust your path.",
  "Always consistent, and let your light shine.",
  "Grow consistent, and believe in your power.",
  "Move consistent, with courage every day.",
  "Stay steady, and keep learning forward.",
  "Stand true, and believe in your power.",
  "Grow consistent, when no one is watching.",
  "Rise open, and lead with heart.",
  "Always strong, and believe in your power.",
  "Always resilient, and trust your path.",
  "Trust ready, and stay the course.",
  "Never present, and the rest will follow.",
  "Push kind, and trust your path.",
  "Rise humble, and trust your path.",
  "Give resilient, and stay the course.",
  "Stand bold, and stay true to your mission.",
  "Rise open, even on tough days.",
  "Grow consistent, through every challenge.",
  "Always clear, and stay the course.",
  "Grow grounded, no matter how hard it gets.",
  "Believe steady, and believe in your power.",
  "Hold resilient, and believe in your power.",
  "Hold going, through every challenge.",
  "Give grounded, with courage every day.",
  "Never open, and lead with heart.",
  "Grow focused, and stay the course.",
  "Move steady, and the rest will follow.",
  "Grow ready, and stay true to your mission.",
  "Never going, when no one is watching.",
  "Focus going, no matter how hard it gets.",
  "Keep hopeful, because you are built for this.",
  "Give strong, and believe in your power.",
  "Push going, because you are capable.",
  "Believe humble, and keep your head high.",
  "Focus present, and believe in your power.",
  "Grow open, and believe in your power.",
  "Be present, and believe in your power.",
  "Stay bold, even on tough days.",
  "Be strong, and keep your spirit strong.",
  "Remember humble, because you are capable.",
  "Stay going, because progress takes time.",
  "Stand steady, and believe in your power.",
  "Grow hopeful, when no one is watching.",
  "Remember resilient, with courage every day.",
  "Work kind, and believe in your power.",
  "Grow grateful, when no one is watching.",
  "Work hopeful, and lead with heart.",
  "Hold motivated, because you are built for this.",
  "Embrace consistent, and keep learning forward.",
  "Push patient, even on tough days.",
  "Remember hopeful, and the rest will follow.",
  "Work ready, because you are built for this.",
  "Focus patient, even on tough days.",
  "Rise resilient, because progress takes time.",
  "Grow true, and keep learning forward.",
  "Trust true, and keep your spirit strong.",
  "Keep patient, because progress takes time.",
  "Work determined, through every challenge.",
  "Move patient, with faith and purpose.",
  "Stay open, because you are built for this.",
  "Remember bold, and lead with heart.",
  "Take motivated, through every challenge.",
  "Always consistent, when no one is watching.",
  "Focus steady, and let your light shine.",
  "Trust steady, and believe in your power.",
  "Give patient, and keep your head high.",
  "Move true, because you are built for this.",
  "Remember steady, and believe in your power.",
  "Remember resilient, and keep your spirit strong.",
  "Work bold, through every challenge.",
  "Work ready, and stay the course.",
  "Focus kind, because you are capable.",
  "Always present, and let your light shine.",
  "Push patient, no matter how hard it gets.",
  "Stand ready, and stay the course.",
  "Rise open, and let your light shine.",
  "Grow strong, and stay the course.",
  "Take true, and keep your head high.",
  "Work present, and stay true to your mission.",
  "Let grateful, when no one is watching.",
  "Work open, and the rest will follow.",
  "Keep patient, and stay the course.",
  "Never strong, when no one is watching.",
  "Focus consistent, and keep learning forward.",
  "Focus true, even on tough days.",
  "Move open, and keep learning forward.",
  "Always open, because you are capable.",
  "Give grounded, when no one is watching.",
  "Focus kind, and trust your path.",
  "Take grateful, and stay true to your mission.",
  "Move kind, because progress takes time.",
  "Always grounded, and lead with heart.",
  "Push steady, and the rest will follow.",
  "Focus determined, until the work pays off.",
  "Take clear, with courage every day.",
  "Let resilient, and stay the course.",
  "Rise open, and trust your path.",
  "Focus grateful, because progress takes time.",
  "Let consistent, and the rest will follow.",
  "Never bold, and keep your head high.",
  "Never open, and let your light shine.",
  "Take bold, even on tough days.",
  "Be steady, and trust your path.",
  "Remember ready, no matter how hard it gets.",
  "Push resilient, until the work pays off.",
  "Work motivated, with faith and purpose.",
  "Take true, through every challenge.",
  "Never strong, no matter how hard it gets.",
  "Stay present, and let your light shine.",
  "Focus grounded, because progress takes time.",
  "Move true, and lead with heart.",
  "Hold open, through every challenge.",
  "Take steady, with faith and purpose.",
  "Believe present, because progress takes time.",
  "Push kind, and trust your path.",
  "Keep consistent, and lead with heart.",
  "Trust grateful, and let your light shine.",
  "Trust consistent, until the work pays off.",
  "Work kind, because you are built for this.",
  "Trust clear, and keep your spirit strong.",
  "Work strong, through every challenge.",
  "Keep steady, and lead with heart.",
  "Hold determined, and stay the course.",
  "Trust steady, with faith and purpose.",
  "Stay focused, no matter how hard it gets.",
  "Grow strong, because progress takes time.",
  "Focus steady, even on tough days.",
  "Embrace hopeful, because you are built for this.",
  "Keep true, and keep your spirit strong.",
  "Work bold, because you are built for this.",
  "Grow strong, and keep learning forward.",
  "Always resilient, and the rest will follow.",
  "Always strong, and stay the course.",
  "Trust open, because you are built for this.",
  "Always true, and keep learning forward.",
  "Always grateful, because you are built for this.",
  "Embrace resilient, and believe in your power.",
  "Grow determined, even on tough days.",
  "Work true, because you are capable.",
  "Let strong, with courage every day.",
  "Hold grateful, and keep your spirit strong.",
  "Take focused, because progress takes time.",
  "Move grateful, and stay the course.",
  "Take focused, when no one is watching.",
  "Stand ready, and believe in your power.",
  "Keep going, because you are capable.",
  "Push determined, and stay true to your mission.",
  "Take clear, because you are built for this.",
  "Never humble, even on tough days.",
  "Never consistent, and keep your spirit strong.",
  "Push kind, through every challenge.",
  "Always ready, and let your light shine.",
  "Believe steady, no matter how hard it gets.",
  "Never steady, with faith and purpose.",
  "Move strong, no matter how hard it gets.",
  "Hold grounded, through every challenge.",
  "Remember present, with faith and purpose.",
  "Take determined, when no one is watching.",
  "Be grounded, and keep your head high.",
  "Always consistent, and believe in your power.",
  "Remember motivated, with courage every day.",
  "Trust true, and stay true to your mission.",
  "Remember determined, and let your light shine.",
  "Hold hopeful, until the work pays off.",
  "Remember open, and trust your path.",
  "Always consistent, and keep your head high.",
  "Move hopeful, and keep your head high.",
  "Rise motivated, and stay the course.",
  "Let focused, and stay true to your mission.",
  "Never open, and the rest will follow.",
  "Always hopeful, and keep learning forward.",
  "Focus kind, no matter how hard it gets.",
  "Stand patient, because you are capable.",
  "Believe clear, with courage every day.",
  "Embrace consistent, even on tough days.",
  "Believe ready, through every challenge.",
  "Stay steady, because you are built for this.",
  "Never motivated, and trust your path."
];


export const feelingCheckInOptions = [
  { emoji: '😊', label: 'Great', value: 5, color: '#10b981', memoji: '/amani-memoji-great.png', expression: 'great' },
  { emoji: '🙂', label: 'Good', value: 4, color: '#84cc16', memoji: '/amani-memoji-good.png', expression: 'good' },
  { emoji: '😐', label: 'Okay', value: 3, color: '#f59e0b', memoji: '/amani-memoji-okay.png', expression: 'okay' },
  { emoji: '😔', label: 'Not Great', value: 2, color: '#f97316', memoji: '/amani-memoji-not-great.png', expression: 'notGreat' },
  { emoji: '😢', label: 'Struggling', value: 1, color: '#ef4444', memoji: '/amani-memoji-struggling.png', expression: 'struggling' }
];

export const moodPrompts = [
  "What's one thing that made you smile today?",
  "How are you feeling about yourself right now?",
  "What's weighing on your mind today?",
  "What would make today feel more manageable?",
  "How connected do you feel to others today?",
  "What's one thing you're grateful for right now?",
  "How is your energy level today?",
  "What do you need most right now?",
  "How are you practicing self-care today?",
  "What would you tell a friend feeling the way you do?"
];
